name: Web-Release

on:
  push:
    branches:
      - main
    paths-ignore:
      - "functions/**"
      - "docs/**"

jobs:
  deploy-prod:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      checks: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install the dependencies
        run: npm install --ci
        env:
          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: true

      - name: Build the application
        run: npm run build

      - uses: FirebaseExtended/action-hosting-deploy@v0.9.0
        with:
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"
          projectId: "${{ secrets.FIREBASE_PROJECT_ID }}"
          channelId: live
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
